### PR TITLE
use heuristics to set cmake env vars when a new prefix is added

### PR DESCRIPTION
**Pull request by g-arjones**
Closes https://github.com/rock-core/autoproj/issues/350

### CODE REVIEW

**Comment by g-arjones** [comment]
Decided not to add `PYTHONPATH` here because:
1. Doesn't require heuristics (all python packages that get installed should add the prefix to the environment)
2. Fetching the actual path requires shelling out to python which we don't want to do for non python packages

**Comment by doudou** [comment]
This is ... nightmarish. Oh well ...

**Review by doudou — APPROVED** [review]

**Comment by g-arjones** [comment]
What do you mean? I can definitely keep this as an extension in a package set if you would rather not have it in autobuild. I'm sharing because I understood you thought it made sense to have.

**Comment by doudou** [comment]
Sorry for the confusion ... it's the lack of CMake normalization that is nightmarish. You had to deal with it (and did it), and I thank you for that ! I would have been too lazy and left things as-is.

**Comment by g-arjones** [comment]
Got it. No problem.

**Pull request merged**
