### PR TITLE
autotools: properly test and fix some corner cases

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by g-arjones** [comment]
Looks good (assuming only test_autotools.rb is relevant here) 👍

**Comment by doudou** [comment]
I would feel better if you could test it on your autotools packages. I don't have any, unfortunately.

**Comment by g-arjones** [comment]
Test watch exactly? #41?

**Comment by g-arjones** [comment]
Ah I see now.. Ok, I'm on it

**Comment by doudou** [comment]
Sorry ... the only relevant commit is: https://github.com/rock-core/autobuild/pull/42/commits/5ee25edfe342c6778abfe0f9a796d3e2b2cc954a. The other one deals with VSCode's inability to have a mixed indent mode :(

**Comment by g-arjones** [comment]
Tested.. It's good! 👍

**Comment by doudou** [comment]
At least now, there are tests ...

**Pull request merged**
