### PR TITLE
git: update the refs in remotes/ in all calls to fetch_commit

### PR DESCRIPTION
**Pull request by doudou**
Fixes https://github.com/rock-core/autoproj/issues/151

### CODE REVIEW

**Comment by g-arjones** [comment]
Have always wondered if that was on purpose. Why does autobuild update the refs by itself rather than doing `git remote update`/`git remote fetch`?

**Comment by doudou** [comment]
> Have always wondered if that was on purpose. Why does autobuild update the refs by itself rather than doing git remote update/git fetch?

Because I got sometimes repositories with branches that were *huge* and not meant for public consumption. So I implemented having autoproj only track the branch it's working on.

It does use `git fetch`, but `git fetch` does not update the refs in `remotes/`

**Comment by g-arjones** [comment]
Fair enough.. Looks good :+1:

**Comment by doudou** [comment]
Another reason: the path to getting a git config is fairly convoluted (source.yml, then overrides). In some cases, the user gets it wrong. To use `remote update`, autobuild has to update the git config first, which would then be broken. Restoring these files being always error-prone, we ensure this way that we update the git config only when we're sure the new config is valid.

For what it's worth, I'm pretty regularly considering that it would be better to just `git remote update`. But then I have these reasons and I'm not sure what's best.

**Comment by g-arjones** [comment]
You lost me on the git config. As far as I can see `git remote update #{remote_name}` should be enough (we are sure that `remote_name` is valid at this point, aren't we?). The downside is that we would be fetching all branches which is definitely a fair point when working with dozens of packages.

**Comment by doudou** [comment]
> we are sure that remote_name is valid at this point, aren't we?

Well, no we're not. The remote configuration is obviously derived from autoproj's configuration, so autobuild has to update the git configuration before it runs `git remote update`. If the user has a typo in his or her source.yml/overrides then the remote will be unusable.

**Comment by g-arjones** [comment]
Well, I expect the command to fail in this case, don't you? I don't see that as a problem at all...

**Comment by doudou** [comment]
My personal experience was that I got annoyed by it. This is why there is an explicit test case for it.

**Pull request merged**
