### PR TITLE
urgent/breaks release: Fix import of tagged packages

### PR DESCRIPTION
**Pull request by goldhoorn**
This fixes:
https://github.com/rock-core/autoproj/issues/77

The problem occurs even on a fresh bootstrap when using the bootstrap.sh script from the rock-release
https://github.com/rock-core/buildconf/blob/rock-15.05/bootstrap.sh

Another option would be to call ```git(package,"reset",pinned_state)``` if this would have unintended side-effects. 

Otherwise please merge asap and create a new gem for autoproj.

### CODE REVIEW

**Comment by goldhoorn** [comment]
@planthaber : please try if this fixes your issue

**Comment by doudou** [comment]
No way I am merging this.

**Comment by doudou** [comment]
And ... did you not try to bootstrap the release before ????

**Comment by goldhoorn** [comment]
The release was bootstrapping fine before the weekend something has changed in the package which causes now a failure.

However, can you do a proper fix or give some details why this is now what you expecting?

**Comment by doudou** [comment]
> And ... did you not try to bootstrap the release before ????

(Not trying to blame, just trying to figure out what happened)

**Comment by goldhoorn** [comment]
I assume it is caused since new commits were pushed to the buildconf.
As i can see autoproj first checks out the master branch and then tries to do a internal update with the reset option given. The problem is that the simple_merge raises the exception i catch. The codeflow later then does the reset as needed.

**Comment by doudou** [comment]
My mistake, sorry. It's close to the right fix, but I interpreted the comment wrongly.

**Comment by doudou** [comment]
updated with a cleaner fix, as well as some related unit tests. Please test.

**Comment by goldhoorn** [comment]
Your patch is working for me, feel free to merge and create the gem

On 08.06.2015 17:24, Sylvain Joyeux wrote:
>
> updated with a cleaner fix, as well as some related unit tests. Please 
> test.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/autobuild/pull/24#issuecomment-110039513>.
>


-- 
  --
  Matthias Goldhoorn
  Unterwasserrobotik
  
  Standort Bremen:
  DFKI GmbH
  Robotics Innovation Center
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Phone: +49 (0)421 218-64100
  Fax:   +49 (0)421 218-64150
  E-Mail: robotik@dfki.de
  
  Weitere Informationen: http://www.dfki.de/robotik
  -----------------------------------------------------------------------
  Deutsches Forschungszentrum fuer Kuenstliche Intelligenz GmbH
  Firmensitz: Trippstadter Straße 122, D-67663 Kaiserslautern
  Geschaeftsfuehrung: Prof. Dr. Dr. h.c. mult. Wolfgang Wahlster
  (Vorsitzender) Dr. Walter Olthoff
  Vorsitzender des Aufsichtsrats: Prof. Dr. h.c. Hans A. Aukes
  Amtsgericht Kaiserslautern, HRB 2313
  Sitz der Gesellschaft: Kaiserslautern (HRB 2313)
  USt-Id.Nr.:    DE 148646973
  Steuernummer:  19/673/0060/3
  -----------------------------------------------------------------------

**Comment by doudou** [comment]
Released 1.9.1 with this patch, checking out rock-15.05 worked for me

**Comment by goldhoorn** [comment]
Please don't forget to create a tag/commit for the release on the repro itself. (make patching easier)

**Comment by doudou** [comment]
is done already

**Pull request merged**
