### PR TITLE
cmake: handle CMAKE_PREFIX_PATH

### PR DESCRIPTION
**Pull request by doudou**
This commit adds the ability to set a list of prefixes globally,
as well as auto-adds the prefixes of the package's direct
dependencies to CMAKE_PREFIX_PATH

### CODE REVIEW

**Comment by goldhoorn** [comment]
ack

**Comment by goldhoorn** [comment]
but why merge into stable?

**Comment by doudou** [comment]
> but why merge into stable?

Good question.

**Comment by goldhoorn** [comment]
pong?

**Comment by doudou** [comment]
Well ... you were the one asking a question ;-)

Anyways, if you're OK with it I'll merge it on master.

**Comment by goldhoorn** [comment]
Feel free to apply it on master (eveb withour a PR)

**Comment by doudou** [comment]
Cherry-picked by hand on master

**Pull request closed without merging**
