### PR TITLE
Make python install compatible with both setuptools and distutils installations

### PR DESCRIPTION
**Pull request by hwiedDFKI**
Please test if it works for you!

### CODE REVIEW

**Comment by hwiedDFKI** [comment]
@2maz ;)

**Comment by hwiedDFKI** [comment]
Fix Install command commit was necessary to get the packages correctly installed the combined command did not work

**Comment by 2maz** [comment]
@hwiedDFKI I think what you want to fix is not a setuptools / disttools issue here, but in your case
rather a package that sets 'build' as alias for 'bdist_wheel'.

**Comment by hwiedDFKI** [comment]
> @hwiedDFKI I think what you want to fix is not a setuptools / disttools issue here, but in your case
> rather a package that sets 'build' as alias for 'bdist_wheel'.

Thank you that's correct! I removed the alias in the setup.cfg and then it works for me.

**Pull request closed without merging**
