### PR TITLE
Added warning if tagged packages are newer than requested tag.

### PR DESCRIPTION
**Pull request by goldhoorn**
This makes autoproj more intuitive in regard to https://github.com/rock-core/autobuild/issues/22

### CODE REVIEW

**Comment by doudou** [comment]
See my comment on https://github.com/rock-core/autobuild/issues/22. This is a too common normal situation when using snapshotting that we really cannot issue warnings for it.

:-1:

**Comment by goldhoorn** [comment]
I continue the discussion from https://github.com/rock-core/autobuild/issues/22 here:

Given the following scenario:
A project uses overrides files (not releases). One of the project member adds a override because master got broken and sets to a defined tag/label.
What will happen: all customers needs to be informed by another communication way. There is no way to recognize that a older version should be used.

From my point of view: If a defined tag/commit is selected in one of the files. A warning is absolutely needed if the repro does not match. Your statement for development is true, but is is a willing and known intended from the developer. Simply not informing the users hides possible problem. Therefore the users gets more confused by NOT warn, instead the developer who GETs warned.

Therefore still a +1 for me.

If we don't come to a consensus i would like to do a ML (-announced doodle) poll.

**Comment by doudou** [comment]
No consensus. Make it a discussion on the ML. This warning will make most snapshot-using installations super noisy, meaning that warnings will simply be ignored.

**Comment by goldhoorn** [comment]
I wrote to the ML, To continue the discussion/give statements:

I thing if a user highly continue a development on a released version of rock, or a snap shot installation he should create a override for the override because he know what he is doing. I see this not as the normal use-case. More as expert-use-case. And as normal, experts should now what they are doing, beginners not. So notify the beginners and possible spam experts if the missed to override their override.

**Comment by doudou** [comment]
This is true, as long as you assume that only experts will use snapshotting. I would very much like this autoproj feature to become standard for a lot of people as it provides a really good safety net (admittedly, we're not there yet)

**Comment by goldhoorn** [comment]
What i mean is that even snapshotting is used by other people they snapshot the current state. If a developer develop a package on a snapshotted release i assume he know that he develops it?

I don't see a case where are several packages are newer than <pin> expect the user has modified it by intention, and then it's valid to give a warning/remember him. Can you maybe give a scenario/workflow where you expect many packages to be modified?

**Comment by doudou** [comment]
Every scenario where I would use "autoproj commit". In these scenarios, the buildconf is giving a working baseline that every team member can refer to and update, while still being able to develop on their own. Updating moves you forward on packages you do not work on, tells you when you diverged, and leaves your work in progress alone. But it also allows you to compare/to reset to a known state whenever you need to. Warnings in this case would basically make the workflow really really annoying.

IMO, your use case (add an override to fix a build) it the typical use case where one should use communication between team members ("you will have to reset package X because master broke it") instead of warnings. Nobody reads autoproj warnings anyways.

**Comment by doudou** [comment]
What *would* work is to display some additional information in the "checked out / updated" message, e.g. 

~~~
updated drivers/transformer
~~~

to get instead

~~~
updated drivers/transformer (2 commits ahead of tag rock-15.05, branch=stable)
~~~

**Comment by goldhoorn** [comment]
The last solution would be fine for me. If i found the time i will have a look for the implementation. If someone else found time, feel free to support

**Comment by goldhoorn** [comment]
However no one seems interested and i don't have the time to implement this i close this

**Pull request closed without merging**
