### PR TITLE
extend python package features

### LINKED ISSUE #106: python_package installation fails because install path isn't on PYTHONPATH
Recently we are facing build errors when building and installing Python packages, e.g.:

    running install
    Checking .pth file support in /home/moooeeeep/workspace/install/some/package/lib/python3.6/site-packages/
    /usr/bin/python3 -E -c pass
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    TEST FAILED: /home/moooeeeep/workspace/install/some/package/lib/python3.6/site-packages/ does NOT support .pth files
    error: bad install directory or PYTHONPATH

    You are attempting to install a package to a directory that is not
    on PYTHONPATH and which Python does not read ".pth" files from.  The
    installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:

        /home/moooeeeep/workspace/install/some/package/lib/python3.6/site-packages/

    and your PYTHONPATH environment variable currently contains:

        ''

    Here are some of your options for correcting the problem:

    * You can choose a different installation directory, i.e., one that is
      on PYTHONPATH or supports .pth files

    * You can add the installation directory to the PYTHONPATH environment
      variable.  (It must then also be on PYTHONPATH whenever you run
      Python and want to use the package(s) you are installing.)

    * You can set up the installation directory to support ".pth" files by
      using one of the approaches described here:

      https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations

    Please make the appropriate changes for your system and try again.

Apparantly the location to which the package is installed needs to be on the PYTHONPATH. Currently the PYTHONPATH entry is added after the installation. As the PYTHONPATH entry is added even when the build fails due to this error, the second run of amake is usually successful. But obviously this is still annoying.

I'm not sure if it is possible to disable this check or the error, to not fail the build. Potentially this is related to the separate prefix dirs setting.

On my machine I usually work around this by adjusting the [install command](https://github.com/rock-core/autobuild/blob/master/lib/autobuild/packages/python.rb#L44) to install to `--user` or via `pip install .`. But maybe this would affect other workflows that rely on these separate installation locations? 

Potentially related: https://github.com/rock-core/autoproj/issues/313

The URL given in the error message is broken, I think it was meant to refer to this content: https://setuptools.pypa.io/en/latest/deprecated/easy_install.html#custom-installation-locations

### PR DESCRIPTION
**Pull request by g-arjones**
Fixes #106 and rock-core/autoproj#313

@moooeeeep Could you please test?

### CODE REVIEW

**Comment by moooeeeep** [comment]
This seems to work for me, thanks!

Any opinions against switching to `pip install . --target=#{prefix}` or similar (and potentially ditching the explicit build step)?

**Comment by g-arjones** [comment]
I would prefer not to, for now af least. I'm in the middle of fixing a lot of things (haven't use the python stuff in a while) and I would have to stop to retest and reassess.

Is there a good reason to use pip for that? That's not what I've seen other build tools do.

**Comment by g-arjones** [comment]
After a quick search it seems we get more control over what happens with setup.py so that's better to integrate. Also pip will try to manage dependencies and I want autoproj to be the tool doing that.

For a user, using pip sounds like a step forward but for a tool I would stick to setup.py

**Review by doudou — APPROVED** [review]

**Comment by moooeeeep** [comment]
You can avoid having pip download dependencies when you pass the `--no-index` flag I believe. Then it should only look among the packages that were already downloaded/installed.

Direct invocations of `setup.py install` are deprecated for more recent versions of setuptools (and further commands might follow). For example this deprecation warning is produced:

    /path/to/ws/install/pip/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.  setuptools.SetuptoolsDeprecationWarning,

Related issue: https://github.com/rock-core/autobuild/issues/108

This workflow will probably be supported for some time. And if users stick to old versions of setuptools, potentially even longer.
But the presence of an explicit `setup.py` file is optional these days. If people start to rely on this, they will run into problems with autobuild.

Most users will probably want to have their packages pip-installable anyways, so they potentially need to maintain their dependencies in several places. But maybe users could also just add their packages as pip osdeps and/or via a custom package index (directory).

For reference:

* https://setuptools.pypa.io/en/latest/build_meta.html
* https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
* https://packaging.python.org/tutorials/packaging-projects/
* https://packaging.python.org/guides/hosting-your-own-index/
* https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-0

But I agree, this is a bigger endeavour. And I'm happy to see, that this PR seems to fix the immediate issue https://github.com/rock-core/autobuild/issues/106.

**Review by moooeeeep — APPROVED** [review]

**Comment by g-arjones** [comment]
I have removed the pytest test utility and left only the fixes for #106 and rock-core/autoproj#313

**Pull request merged**
