### PR TITLE
[DO NOT MERGE] Manage compilation flags

### LINKED ISSUE #50: manage C[XX]FLAGS environment variable to setup include dirs
This would ease integration of cmake/autotools packages that do not provide a pkg-config file, specially with autoproj's "separate prefixes" option. The idea is to patch `Autobuild::Environment#add_prefix` to append `-I#{new_prefix}` and `-L#{new_prefix}` to `CFLAGS`, `CXXFLAGS` and `LDFLAGS` if the new prefix contains an `include/` and/or `lib/` folder  (filtering out possible dupes)

### PR DESCRIPTION
**Pull request by g-arjones**
This is still a work in progress, there are some TODO notes with what needs to be done on the `#add_prefix` method. @doudou very interested in your thoughts on this...

Closes #50

### CODE REVIEW

**Comment by g-arjones** [comment]
Maybe it would be better to append the flags in the relevant package handlers rather than in #add_prefix... Then we wouldn't need what's described in the TODO notes..

**Comment by doudou** [comment]
What follows might very well be what you meant with `Maybe it would be better to append the flags in the relevant package handlers rather than in #add_prefix`, in which case we completely agree ;-)

Generally speaking, as I understand it, this would allow to add the relevant flags to packages that depend on other packages that don't have a "good" way to deal with flag-setting (pkg-config or cmake).

This in my opinion is a problem that *these* packages should deal with, not autoproj. In other words, the target package (the one that needs the flags) should be able to find the prefix of the source package (the one that provides no way to deal with them) and compute its flags. I would be all OK with having helpers for these in the relevant package types (Autotools/CMake), for instance taking the package name and/or prefix, then computing and adding the flags.

Adding them to the environment will eventually leak into the global environment which is obviously wrong.

Autoproj is not meant to be a magical build system, but rather allow to automate things that humans have to do manually. More Ansible than Chef ;-)

**Comment by g-arjones** [comment]
> Generally speaking, as I understand it, this would allow to add the relevant flags to packages that depend on other packages that don't have a "good" way to deal with flag-setting (pkg-config or cmake).

Not all flags, linking dependencies, c++ release and pretty much all package-specific stuff are not supposed to be handled with this.

> Adding them to the environment will eventually leak into the global environment which is obviously wrong.

Why do you think that's wrong? I mean, all source packages should look for headers in `#{Autoproj.prefix}/include` and libs (at least) in `#{Autoproj.prefix}/lib` regardless of their dependencies, shouldn't they? I think the rationale is the same for `LD_LIBRARY_PATH`, one could compile with `-rpath #{Autoproj.prefix}/lib` and handle that on a per-package basis but instead, since it would be required in all packages, we handle that in the environment. To be clear, these flags are specific to the workspace, not to a single package.

That being said, I would accept to add these flags in my buildconf's init.rb if you don't like what this patch does and/or really don't think autoproj should handle this.

**Comment by doudou** [comment]
> regardless of their dependencies, shouldn't they?

Actually not. Eigen -> `include/eigen3`. Packages commonly would install in a subfolder but assume that the include path has this subfolder. There is no universal rule, and assuming that there is one is just calling for trouble.

> To be clear, these flags are specific to the workspace, not to a single package.

Well, they are specific to a package as soon as you use the separate prefixes feature (i.e. CI support). Using `separate_prefixes` should become the norm at some point (a.k.a. as soon as I have enough time to write more about it), it really has a lot of good effects - but breaks builds because it's a lot more strict on the dependencies. If the goal is to set global compilation and linking flags, then :-1:

> That being said, I would accept to add these flags in my buildconf's init.rb if you don't like what this patch does and/or really don't think autoproj should handle this.

You'll have to do that, then. I don't see a world where setting *global* compile and link flags makes sense at the tool level.

**Comment by g-arjones** [comment]
> Eigen -> include/eigen3. Packages commonly would install in a subfolder but assume that the include path has this subfolder.

Even in these cases, the compiler still looks in the parent folder (when the packages are installed in the system, even if you pass -I/usr/include/eigen3, the compiler still looks in /usr/include). In fact this is the most common use case and not a problem, at all.

> calling for trouble.

Can't see what kind of trouble this would cause. These -I and -L flags are just search paths, no different then i.e `PYTHONPATH` and `RUBYLIB`. and would be used on top of what is retrieved from pkg-config, so packages that provide .pc files would not be affected.

Anyway, this is not a big deal. I can live with `Autoproj.env.set 'CFLAGS', "#{Autoproj.prefix}/include"` in my init script. Feel free to close this and rock-core/autoproj#192 as well.. :+1:

**Comment by doudou** [comment]
> Can't see what kind of trouble this would cause.

Fair enough ... the compilers do add the base include path to the include directory.

What I am puzzled about is the following: if you *need* these include paths to be explicitely added

**Comment by g-arjones** [comment]
> if you need these include paths to be explicitely added

How else would the compiler find headers there?

**Comment by doudou** [comment]
> How else would the compiler find headers there?

Damn ... I did not intend to send this message at all, so half-terminated sentence.

Basically, what's wrong for me is that generally speaking if you have a dependency, then it is your build system's job to make sure you have the right flags. Doing what you do here globally makes no sense for this particular reason. A good fix for packages that don't provide a way to deal with this is what I proposed (an API on packages that allows one package to try to auto-guess the compilation and library flags for a particular dependency).

Generally speaking, autoproj/autobuild should not have to deal with this. I know that it's not always possible, but having it done globally only hides the issues.

**Comment by g-arjones** [comment]
I see... Fair enough, thanks for the insights, as always :+1:

**Pull request closed without merging**
