### PR TITLE
improve update outcome reporting with colors and better messages

### PR DESCRIPTION
**Pull request by doudou**
This improves the new "updated/up-to-date" distinction to handle
the interrupted and error cases. Moreover, it adds colors, which makes
visually parsing updated vs. up-to-date easier as well.

### CODE REVIEW

**Comment by doudou** [comment]
@g-arjones what do you think of that ?

**Comment by g-arjones** [comment]
I like it.. The colors are great visual cue.
The exception situation is improved but not solved yet, feels like a race condition of some sort (in autoproj, I believe)

**Comment by doudou** [comment]
> The exception situation is improved but not solved yet

Could you give me something to reproduce ?

**Comment by g-arjones** [comment]
Just realized it only happens if you use the 'aup/amake' aliases. `autoproj update` works as expected

**Pull request merged**
